### ISSUE TITLE
UI issues in Dragonflight

### ISSUE THREAD

**Issue by Spudmonk3y** [doadin/PlexusClickSets#4]
UI in dragonflight shows only ctrl+shift going down the line, this is a graphical bug as changing the value does update the corresponding button combination if it's done in the correct spot of the list.  

The available mouse buttons extend well beyond the bounds of the box, clicking them does not update the view, but clicking one and then making a change will apply it to the correct button.

Essentially the view appears to never update after the initial load, but the functionality still works so you can set your clicksets, but you have to do it blindly.  

![image](https://user-images.githubusercontent.com/52615468/202917477-2268d289-0f82-4ec3-958f-35d13185f700.png)

**Comment by doadin** [comment]
Fixed:
https://github.com/doadin/PlexusClickSets/commit/a8c364121060a48622e18b8cb09383b263a11fd5
https://github.com/doadin/PlexusClickSets/commit/2c5d22ca496a5ca4c27eb836f54c098a6ac55c43

**Comment by doadin** [comment]
Look for v1.3.4 . This version has these fixes in it.

**Comment by Spudmonk3y** [comment]
Update looks good, thanks for the fast turnaround, sorry for the delayed confirmation.
